package com.kostadin.sis.config.mail.template;

public enum TemplateId {
    ABSENCE_CREATE_EMAIL_ABSENT_USER,
    ABSENCE_CREATE_EMAIL_TEAM,
    ABSENCE_CREATE_EMAIL_SUBSTITUTE,
    ABSENCE_UPDATE_EMAIL_ABSENT_USER,
    ABSENCE_UPDATE_EMAIL_TEAM,
    ABSENCE_UPDATE_EMAIL_SUBSTITUTE,
    ABSENCE_DELETE_EMAIL_ABSENT_USER,
    ABSENCE_DELETE_EMAIL_TEAM,
    ABSENCE_DELETE_EMAIL_SUBSTITUTE,
    ABSENCE_UPDATE_EMAIL_OLD_SUBSTITUTE,
    ABSENCE_UPDATE_EMAIL_NEW_SUBSTITUTE,
    PASSWORD_RESET_REQUEST_EMAIL,
    PASSWORD_RESET_SUCCESS_EMAIL
}
