--liguidbase formatted sql

--changes kostadin:users-table
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMPLOYEE_NUMBER VARCHAR(8) UNIQUE NOT NULL,
    PHONE VARCHAR(10) UNIQUE,
    SECONDARY_PHONE VARCHAR(10) UNIQUE,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    SECONDARY_EMAIL VARCHAR(255) UNIQUE,
    COMPANY VARCHAR(255),
    ROLE VARCHAR(255) NOT NULL,
    COLOR VARCHAR(7) NOT NULL
);

--changes kostadin:absences-table
CREATE TABLE ABSENCES (
    ID SERIAL PRIMARY KEY,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    ABSENCE_TYPE VARCHAR(255) NOT NULL,
    BOOKED_DATE DATE,
    USER_ID INT,
    SUBSTITUTE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (SUBSTITUTE_ID) REFERENCES USERS(ID)
);

--changes kostadin:projects-table
CREATE TABLE PROJECTS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    STATUS VARCHAR(255) NOT NULL,
    CAPACITY_MODE BOOLEAN NOT NULL,
    PROJECT_OWNER_ID INT NOT NULL,
    FOREIGN KEY (PROJECT_OWNER_ID) REFERENCES USERS(ID)
);

--changes kostadin:labels-table
CREATE TABLE LABELS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SCOPE VARCHAR(255) NOT NULL
);

--changes kostadin:project_user-table
CREATE TABLE PROJECT_USER (
    CAPACITY INT NOT NULL,
    USER_ID INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

--changes kostadin:project_label-table
CREATE TABLE PROJECT_LABEL (
    PROJECT_ID INT NOT NULL,
    LABEL_ID INT NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
    FOREIGN KEY (LABEL_ID) REFERENCES LABELS(ID)
);

--changes kostadin:user_label-table
CREATE TABLE USER_LABEL (
    USER_ID INT NOT NULL,
    LABEL_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (LABEL_ID) REFERENCES LABELS(ID)
);

--changes kostadin:subscriptions-table
CREATE TABLE SUBSCRIPTIONS (
    USER_ID INT NOT NULL,
    SUBSCRIBER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (SUBSCRIBER_ID) REFERENCES USERS(ID)
);

--changes kostadin:year_entries-table
CREATE TABLE YEAR_ENTRIES (
    ID SERIAL PRIMARY KEY,
    YEAR_ENTRY VARCHAR(4) UNIQUE NOT NULL,
    NON_WORKING_DAYS TEXT NOT NULL
);
